"""Added mobile login and OTP system

Revision ID: 727f27466503
Revises: a02eb04e44a2
Create Date: 2026-04-28 20:24:29.200617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727f27466503'
down_revision = 'a02eb04e44a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_mobile_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_user_mobile', ['mobile'])
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_mobile_verified')
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('mobile')

    # ### end Alembic commands ###
